import React, { Component } from 'react';
import './App.css';

import img20000Leagues from './assets/images/20000leaguesunderthesea.jpg';
import img2001 from './assets/images/2001.jpg';
import American from './assets/images/americangods.jpg';
import Anathem from './assets/images/anathem.jpg';
import Assassins from './assets/images/assassinsapprentice.jpg';
import BookOfThe from './assets/images/bookofthenewsun.jpg';
import BraveNew from './assets/images/bravenewworld.jpg';
import CatsCradle from './assets/images/catscradle.jpg';
import Childhoods from './assets/images/childhoodsend.jpg';
import Clockwork from './assets/images/clockworkorange.jpg';
import Contact from './assets/images/contact.jpg';
import Cryptonomicon from './assets/images/cryptonomicon.jpg';
import DoAndroids from './assets/images/doandroidsdreamofelectricsheep.jpg';
import Dragonflight from './assets/images/dragonflight.jpg';
import Dune from './assets/images/dune.jpg';
import EndersGame from './assets/images/endersgame.jpg';
import EyeOfThe from './assets/images/eyeoftheworld.jpg';
import Foundation from './assets/images/foundation.jpg';
import FuriesOf from './assets/images/furiesofcalderon.jpg';
import GameOfThrones from './assets/images/gameofthrones.jpg';
import GardensOf from './assets/images/gardensofthemoon.jpg';
import Gunslinger from './assets/images/gunslinger.jpg';
import Handmaids from './assets/images/handmaidstale.jpg';
import Hitchhikers from './assets/images/hitchhikersguidetothegalaxy.jpg';
import Homeland from './assets/images/homeland.jpg';
import LastUnicorn from './assets/images/lastunicorn.jpg';
import LordOfThe from './assets/images/lordoftherings.jpg';
import Martian from './assets/images/martianchronicles.jpg';
import Mistborn from './assets/images/mistborn.jpg';
import MistsOf from './assets/images/mistsofavalon.jpg';
import MoonIs from './assets/images/moonisaharshmistress.jpg';
import NameOfThe from './assets/images/nameofthewind.jpg';
import Neuromancer from './assets/images/neuromancer.jpg';
import Neverwhere from './assets/images/neverwhere.jpg';
import Nineteen from './assets/images/nineteeneightyfour.jpg';
import OnceAnd from './assets/images/onceandfutureking.jpg';
import PrincessBride from './assets/images/princessbride.jpg';
import Rendezvous from './assets/images/rendezvouswithrama.jpg';
import Ringworld from './assets/images/ringworld.jpg';
import Silmarillion from './assets/images/silmarillion.jpg';
import Slaughterhouse from './assets/images/slaughterhousefive.jpg';
import SnowCrash from './assets/images/snowcrash.jpg';
import Starship from './assets/images/starshiptroopers.jpg';
import StrangerIn from './assets/images/strangerinastrangeland.jpg';
import TimeMachine from './assets/images/timemachine.jpg';
import WarOfThe from './assets/images/waroftheworlds.jpg';
import WatershipDown from './assets/images/watershipdown.jpg';
import WayOfKings from './assets/images/wayofkings.jpg';


class App extends Component {
  state = {
    displayAll: true,
    books: [
      {name: '2001, A Space Odyssey', author: 'Arthur C. Clarke', date: 1968, image: img2001, selected: 'false', description: '2001: A Space Odyssey is a 1968 science fiction novel by British writer Arthur C. Clarke. It was developed concurrently with Stanley Kubrick\'s film version and published after the release of the film. Clarke and Kubrick worked on the book together, but eventually only Clarke ended up as the official author. The story is based in part on various short stories by Clarke, including "The Sentinel" (written in 1948 for a BBC competition, but first published in 1951 under the title "Sentinel of Eternity"). By 1992, the novel had sold three million copies worldwide. An elaboration of Clarke and Kubrick\'s collaborative work on this project was made in The Lost Worlds of 2001.'},
      {name: '20000 Leagues Under the Sea', author: 'Jules Verne', date: 1870, image: img20000Leagues, selected: 'false', description: 'Twenty Thousand Leagues Under the Seas: A Tour of the Underwater World (French: Vingt mille lieues sous les mers: Tour du monde sous-marin, "Twenty Thousand Leagues Under the Seas: A Tour of the Underwater World") is a classic science fiction adventure novel by French writer Jules Verne published in 1870. The novel was originally serialized from March 1869 through June 1870 in Pierre-Jules Hetzel\'s periodical, the Magasin d\'Éducation et de Récréation. The deluxe illustrated edition, published by Hetzel in November 1871, included 111 illustrations by Alphonse de Neuville and Édouard Riou. The book was highly acclaimed when it was released and still is; it is regarded as one of the premiere adventure novels and one of Verne\'s greatest works, along with Around the World in Eighty Days and Journey to the Center of the Earth. The description of Nemo\'s ship, the Nautilus, was considered ahead of its time, as it accurately describes features on submarines, which at the time were very primitive vessels.'},
      {name: 'American Gods', author: 'Neil Gaiman', date: 2001, image: American, selected: 'false', description: 'American Gods (2001) is a novel by English author Neil Gaiman. The novel is a blend of Americana, fantasy, and various strands of ancient and modern mythology, all centering on the mysterious and taciturn Shadow. The book was published in 2001 by Headline in the United Kingdom and by William Morrow in the United States. It gained a positive critical response and won the Hugo and Nebula awards in 2002. A special tenth anniversary edition, which includes the "author\'s preferred text" and 12,000 additional words, was published in June 2011 by William Morrow. Two audio versions of the book were produced and published by Harper Audio: an unabridged version of the original published edition, read by George Guidall, released in 2001; and a full cast audiobook version of the tenth anniversary edition, released in 2011. In March 2017, The Folio Society published a special collector\'s edition of American Gods, with many corrections to the author\'s preferred text version. In April 2017, Starz began airing a television adaptation of the novel. Bryan Fuller and Michael Green served as showrunners, and Gaiman is an executive producer. Fuller and Green departed the show after the first season.'},
      {name: 'Anathem', author: 'Neal Stephenson', date: 2008, image: Anathem, selected: 'false', description: 'Anathem is a science fiction novel by American writer Neal Stephenson, published in 2008. Major themes include the many-worlds interpretation of quantum mechanics and the philosophical debate between Platonic realism and nominalism. Anathem is set on and around the fictional planet Arbre. Thousands of years before the events in the novel, the planet\'s intellectuals entered concents (monastic communities) to protect their activities from the collapse of society. The avout (intellectuals separated from Sæcular society) retain extremely limited access to tools and are banned from possessing or operating most advanced technology and are supervised by the Inquisition, which answers to the outside world. The avout are allowed to communicate with people outside the walls of the concent only once every year, decade, century, or millennium, depending on the particular vows they have taken.'},
      {name: 'Assassin\'s Apprentice', author: 'Robin Hobb', date: 1995, image: Assassins, selected: 'false', description: 'Assassin\'s Apprentice is a fantasy novel by American writer Robin Hobb, the first in her Farseer Trilogy. It was Margaret Astrid Lindholm Ogden\'s first book under this pseudonym, and was published in 1995. The book was written under the working title Chivalry’s Bastard. The stories of characters found in the Farseer Trilogy continue in the Tawny Man Trilogy and the Fitz and the Fool Trilogy. Other series, The Liveship Traders and The Rain Wild Chronicles, are set in the same world and in the same timeframe, with some crossover. The novel covers the early life of FitzChivalry, a royal Illegitimacy living in Buckkeep Castle as he begins his training as an assassin and successfully safeguards the throne from his over-ambitious uncle Regal, almost at the cost of his life.'},
      {name: 'Brave New World', author: 'Aldous Huxley', date: 1932, image: BraveNew, selected: 'false', description: 'Brave New World is a dystopian novel written in 1931 by English author Aldous Huxley, and published in 1932. Largely set in a futuristic World State of genetically modified citizens and an intelligence-based social hierarchy, the novel anticipates huge scientific developments in reproductive technology, sleep-learning, psychological manipulation, and classical conditioning that are combined to make a utopian society that goes challenged only by a single outsider. Huxley followed this book with a reassessment in an essay, Brave New World Revisited (1958), and with Island (1962), his final novel. In 1999, the Modern Library ranked Brave New World fifth on its list of the 100 best English-language novels of the 20th century. In 2003, Robert McCrum writing for The Observer included Brave New World chronologically at number 53 in "the top 100 greatest novels of all time", and the novel was listed at number 87 on the BBC\'s survey The Big Read.'},
      {name: 'The Book of the New Sun', author: 'Gene Wolfe', date: 1980, image: BookOfThe, selected: 'false', description: 'The Book of the New Sun (1980 – 1983) is a series of four science fantasy novels or one four-volume novel written by American author Gene Wolfe. Alternatively, it is a series comprising the original tetralogy, a 1983 collection of essays, and a 1987 sequel. Either way, it inaugurated the so-called "Solar Cycle" that Wolfe continued after 1987 by setting other multi-volume works in the same universe. Gene Wolfe had originally intended the story to be a 40,000-word novella called "The Feast of Saint Catherine", meant to be published in one of the Orbit anthologies, but during the writing it continued to grow in size. Despite being published with a year between each book, all four books were written and completed during his free time without anyone\'s knowledge when he was still an editor of Plant Engineering, allowing him to write at his own pace and take his time. The tetralogy chronicles the journey of Severian, a disgraced journeyman torturer who is exiled and forced to travel to Thrax and beyond. It is a first-person narrative, apparently translated by Wolfe into contemporary English, set in the distant future when the Sun has dimmed and Earth is cooler (a "Dying Earth" story).'},
      {name: 'Cat\'s Cradle', author: 'Kurt Vonnegut, Jr', date: 1963, image: CatsCradle, selected: 'false', description: 'Cat\'s Cradle is a science fiction novel by American writer Kurt Vonnegut, first published in 1963. His fourth novel, it explores issues of science, technology, and religion, satirizing the arms race and many other targets along the way. After turning down his original thesis in 1947, the University of Chicago awarded Vonnegut his master\'s degree in anthropology in 1971 for Cat\'s Cradle. The title of the book derives from the string game "cat\'s cradle". Early in the book, the character Felix Hoenikker (a fictional co-inventor of the atom bomb) was playing cat\'s cradle when the bomb was dropped, and the game is later referred to by his son, Newton Hoenikker.'},
      {name: 'Childhood\'s End', author: 'Arthur C. Clarke', date: 1953, image: Childhoods, selected: 'false', description: 'Childhood\'s End is a 1953 science fiction novel by the British author Arthur C. Clarke. The story follows the peaceful alien invasion of Earth by the mysterious Overlords, whose arrival begins decades of apparent utopia under indirect alien rule, at the cost of human identity and culture. Clarke\'s idea for the book began with his short story "Guardian Angel" (1946), which he expanded into a novel in 1952, incorporating it as the first part of the book, "Earth and the Overlords". Completed and published in 1953, Childhood\'s Endsold out its first printing, received good reviews and became Clarke\'s first successful novel. The book is often regarded by both readers and critics as Clarke\'s best novel and is described as "a classic of alien literature". Along with The Songs of Distant Earth (1986), Clarke considered Childhood\'s End to be one of his favourites of his own novels. The novel was nominated for the Retro Hugo Award for Best Novel in 2004.'},
      {name: 'A Clockwork Orange', author: 'Anthony Burgess', date: 1962, image: Clockwork, selected: 'false', description: 'A Clockwork Orange is a dystopian satirical black comedy novel by English writer Anthony Burgess, published in 1962. It is set in a near future English society featuring a subculture of extreme youth violence. The teenage protagonist, Alex, narrates his violent exploits and his experiences with state authorities intent on reforming him. The book is partially written in a Russian-influenced argot called "Nadsat", which takes its name from the Russian suffix that is equivalent to \'-teen\' in English. According to Burgess, it was a jeu d\'esprit written in just three weeks. In 2005, A Clockwork Orange was included on Time magazine\'s list of the 100 best English-language novels written since 1923, and it was named by Modern Library and its readers as one of the 100 best English-language novels of the 20th century. The original manuscript of the book has been located at McMaster University\'s William Ready Division of Archives and Research Collections in Hamilton, Ontario, Canada since the institution purchased the documents in 1971.'},
      {name: 'Cryptonomicon', author: 'Neil Stephenson', date: 1999, image: Cryptonomicon, selected: 'false', description: 'Cryptonomicon is a 1999 novel by American author Neal Stephenson, set in two different time periods. One group of characters are World War II-era Allied codebreakers and tactical-deception operatives affiliated with the Government Code and Cypher School at Bletchley Park (UK), and disillusioned Axis military and intelligence figures. The second narrative is set in the late 1990s, with characters that are (in part) descendants of those of the earlier time period, who employ cryptologic, telecom, and computer technology to build an underground data haven in the fictional Sultanate of Kinakuta. Their goal is to facilitate anonymous Internet banking using electronic money and (later) digital gold currency, with a long-term objective to distribute Holocaust Education and Avoidance Pod (HEAP) media for instructing genocide-target populations on defensive warfare.'},
      {name: 'Contact', author: 'Carl Sagan', date: 1985, image: Contact, selected: 'false', description: 'Contact is a 1985 science fiction novel by American scientist Carl Sagan. It deals with the theme of contact between humanity and a more technologically advanced, extraterrestrial life form. It ranked No. 7 on the 1985 U.S. bestseller list. The novel originated as a screenplay by Sagan and Ann Druyan (whom he later married) in 1979; when development of the film stalled, Sagan decided to convert the stalled film into a novel. The film concept was subsequently revived and eventually released in 1997 as the film Contact starring Jodie Foster.'},
      {name: 'Do Androids Dream of Electric Sheep', author: 'Philip K. Dick', date: 1968, image: DoAndroids, selected: 'false', description: 'Do Androids Dream of Electric Sheep? (retitled Blade Runner: Do Androids Dream of Electric Sheep? in some later printings) is a science fiction novel by American writer Philip K. Dick, first published in 1968. The novel is set in a post-apocalyptic San Francisco, where Earth\'s life has been greatly damaged by nuclear global war. Most animal species are endangered or extinct from extreme radiation poisoning, so that owning an animal is now a sign of status and empathy, an attitude encouraged towards animals. The book served as the primary basis for the 1982 film Blade Runner, and many elements and themes from it were used in its 2017 sequel Blade Runner 2049. The main plot follows Rick Deckard, a bounty hunter who is tasked with "retiring" (i.e. killing) six escaped Nexus-6 model androids, while a secondary plot follows John Isidore, a man of sub-par IQ who aids the fugitive androids. In connection with Deckard\'s mission, the novel explores the issue of what it is to be human and whether empathy is a purely human ability.'},
      {name: 'Dragonflight', author: 'Anne McCaffrey', date: 1968, image: Dragonflight, selected: 'false', description: 'Dragonflight is a science fiction novel by the American-Irish author Anne McCaffrey. It is the first book in the Dragonriders of Pern series. Dragonflight was first published by Ballantine Books in July 1968. It is a fix-up of novellas, including two which made McCaffrey the first woman writer to win a Hugo and Nebula Award. In 1987, Locus: The magazine of the science fiction & fantasy field ranked Dragonflight at number nine among the 33 "All-Time Best Fantasy Novels", based on a poll of subscribers.'},
      {name: 'Dune', author: 'Frank Herbert', date: 1965, image: Dune, selected: 'false', description: 'Dune is a 1965 science fiction novel by American author Frank Herbert, originally published as two separate serials in Analog magazine. It tied with Roger Zelazny\'s This Immortal for the Hugo Award in 1966, and it won the inaugural Nebula Award for Best Novel. It is the first installment of the Dune saga, and in 2003 was cited as the world\'s best-selling science fiction novel. Set in the distant future amidst a feudal interstellar society in which noble houses, in control of individual planets, owe allegiance to the Padishah Emperor, Dune tells the story of young Paul Atreides, whose noble family accepts the stewardship of the desert planet Arrakis. As this planet is the only source of the oracular spice melange, the most important and valuable substance in the universe, control of Arrakis is a coveted—and dangerous—undertaking. The story explores the multi-layered interactions of politics, religion, ecology, technology, and human emotion, as the factions of the empire confront each other in a struggle for the control of Arrakis and its spice.'},
      {name: 'Enders Game', author: 'Orson Scott Card', date: 1985, image: EndersGame, selected: 'false', description: 'Ender\'s Game is a 1985 military science fiction novel by American author Orson Scott Card. Set at an unspecified date in Earth\'s future, the novel presents an imperiled mankind after two conflicts with the Formics, an insectoid alien species which they dub the "buggers". In preparation for an anticipated third invasion, children, including the novel\'s protagonist, Andrew "Ender" Wiggin, are trained from a very young age through increasingly difficult games including some in zero gravity, where Ender\'s tactical genius is revealed. The book originated as the short story "Ender\'s Game", published in the August 1977 issue of Analog Science Fiction and Fact. Elaborating on characters and plot lines depicted in the novel, Card later wrote additional books to form the Ender\'s Game series. Card released an updated version of Ender\'s Game in 1991, changing some political facts to reflect the times more accurately; e.g., to include the collapse of the Soviet Union and the end of the Cold War.'},
      {name: 'The Eye of the World', author: 'Robert Jordan', date: 1990, image: EyeOfThe, selected: 'false', description: 'The Eye of the World is a fantasy novel by American writer Robert Jordan, the first book of The Wheel of Time series. It was published by Tor Books and released on January 16, 1990. The unabridged audiobook is read by Michael Kramer and Kate Reading. Upon first publication, The Eye of the World consisted of one prologue and 53 chapters, with an additional prologue authored upon re-release. On January 2, 2002, The Eye of the World was re-released as two separate books aimed at a young adult literaturemarket, with larger text and a handful of illustrations. These were From the Two Rivers and To the Blight. The former included an additional prologue entitled "Ravens", focusing on Egwene al\'Vere. The American Library Association put The Eye of the World on its 2003 list of Popular Paperbacks for Young Adults.'},
      {name: 'A Game of Thrones', author: 'George R.R. Martin', date: 1996, image: GameOfThrones, selected: 'false', description: 'A Game of Thrones is the first novel in A Song of Ice and Fire, a series of fantasy novels by American author George R. R. Martin. It was first published on August 1, 1996. The novel won the 1997 Locus Award and was nominated for both the 1997 Nebula Award and the 1997 World Fantasy Award. The novella Blood of the Dragon, comprising the Daenerys Targaryen chapters from the novel, won the 1997 Hugo Award for Best Novella. In January 2011 the novel became a New York Times Bestseller and reached #1 on the list in July 2011. In the novel, recounting events from various points of view, Martin introduces the plot-lines of the noble houses of Westeros, the Wall, and the Targaryens. The novel has inspired several spin-off works, including several games. It is also the namesake and basis for the first season of Game of Thrones, an HBO television series that premiered in April 2011. A March 2013 paperback TV tie-in re-edition was also titled Game of Thrones, excluding the indefinite article "A".'},
      {name: 'Gardens of the Moon', author: 'Steven Erikson', date: 1999, image: GardensOf, selected: 'false', description: 'Gardens of the Moon is the first of ten novels in Canadian author Steven Erikson\'s high fantasy series the Malazan Book of the Fallen. It was first published in 1999 and was nominated for a World Fantasy Award. The novel details the various struggles for power on an intercontinental region dominated by the Malazan Empire. It is notable for the use of high magic, and unusual plot structure. Gardens of the Moon centres around the Imperial campaign to conquer the city of Darujhistan on the continent of Genabackis. The novel opens in the 96th year of the Malazan Empire, during the final year of the rule of Emperor Kellanved. A young boy, aged 12, named Ganoes Paran witnesses the sacking of the Mouse Quarter of Malaz City. Paran wants to be a soldier when he grows older, though the veteran soldier Whiskeyjack disapproves.'},
      {name: 'The Gunslinger', author: 'Stephen King', date: 1982, image: Gunslinger, selected: 'false', description: 'The Gunslinger is a fantasy novel by American author Stephen King, the first volume in the Dark Tower series. The Gunslinger was first published in 1982 as a fix-up novel, joining five short stories that had been published between 1978 and 1981. King substantially revised the novel in 2003, and this version is in print today. The story centers upon Roland Deschain, the last gunslinger, who has been chasing after his adversary, "the man in black," for many years. The novel fuses Western fiction with fantasy, science fiction and horror, following Roland\'s trek through a vast desert and beyond in search of the man in black. Roland meets several people along his journey, including a boy named Jake Chambers who travels with him part of the way.'},
      {name: 'The Handmaid\'s Tail', author: 'Margeret Atwood', date: 1985, image: Handmaids, selected: 'false', description: 'The Handmaid\'s Tale is a dystopian novel by Canadian author Margaret Atwood, originally published in 1985. It is set in a near-future New England, in a totalitarian state resembling a theonomy, which has overthrown the United States government. The novel focuses on the journey of the handmaid Offred. Her name derives from the possessive form "of Fred"; handmaids are forbidden to use their birth names and must echo the male, or master, whom they serve. The Handmaid\'s Tale explores themes of women in subjugation in a patriarchal society and the various means by which these women attempt to gain individualism and independence. The novel\'s title echoes the component parts of Geoffrey Chaucer\'s The Canterbury Tales, which is a series of connected stories ("The Merchant\'s Tale", "The Parson\'s Tale", etc.). The Handmaid\'s Tale is structured into two parts, night and other various events. This novel can be interpreted as a double narrative, Offred\'s tale and the handmaids\' tales. The night sections are solely about Offred, and the other sections (shopping, waiting room, household, etc.) are the stories that describe the possible life of every handmaid, though from the perspective of Offred.'},
      {name: 'The Foundation Trilogy', author: 'Isaac Asimov', date: 1951, image: Foundation, selected: 'false', description: 'Foundation is a science fiction novel by American writer Isaac Asimov. It is the first published in his Foundation Trilogy(later expanded into the Foundation Series). Foundation is a cycle of five interrelated short stories, first published as a single book by Gnome Press in 1951. Collectively they tell the early story of the Foundation, an institute to preserve the best of galactic civilization after the collapse of the Galactic Empire. Four of the five stories had been earlier published in Astounding Science Fiction between 1942 and 1944 under different titles. A fifth part, the first in terms of fictional chronology, was added for the 1951 Gnome Press edition. The original four stories also appeared in 1955 as part of Ace Double\'s novel series as D-110 under the title The 1,000-Year Plan. Two further books, each consisting of two novellas, were published shortly after and the three are considered a trilogy. Asimov would write two further sequel novels and two prequels. Later writers have written new additions authorized by Asimov\'s estate. The Foundation Series is often regarded as one of Isaac Asimov\'s best works, alongside his Robot series.'},
      {name: 'Furies of Calderon', author: 'Jim Butcher', date: 2004, image: FuriesOf, selected: 'false', description: 'Furies of Calderon is the first novel in the high fantasy series Codex Alera by Jim Butcher. The novel was first released by Ace Books in the United States as a Hardcover edition on October 5, 2004, followed by a Paperback edition on June 26, 2005. Orbit Books released a paperback edition in the United Kingdom in December 2009. It tells the story of a young boy named Tavi who is the only one without any fury crafting abilities. The novel was well received, with critics praising Butcher\'s turn at a more traditional fantasy setting, fast pacing, action, and his characterization of the antagonists.'},
      {name: 'The Hitchhiker\'s Guide To The Galaxy', author: 'Douglas Adams', date: 1979, image: Hitchhikers, selected: 'false', description: 'The Hitchhiker\'s Guide to the Galaxy is the first of five books in the Hitchhiker\'s Guide to the Galaxy comedy science fiction "trilogy" by Douglas Adams. The novel is an adaptation of the first four parts of Adams\' radio series of the same name. The novel was first published in London on 12 October 1979. It sold 250,000 copies in the first three months. The namesake of the novel is The Hitchhiker\'s Guide to the Galaxy, a fictional guide book for hitchhikers (inspired by the Hitch-hiker\'s Guide to Europe) written in the form of an encyclopedia.'},
      {name: 'Homeland', author: 'R.A. Salvatore', date: 1990, image: Homeland, selected: 'false', description: 'Homeland is a fantasy novel by American writer by R. A. Salvatore, the first book in The Dark Elf Trilogy, a prequel to The Icewind Dale Trilogy. It follows the story of Drizzt Do\'Urden from the time and circumstances of his birth and his upbringing amongst the drow (dark elves). The book takes the reader into Menzoberranzan, the city of drow that is Drizzt\'s homeland. From here, the reader follows Drizzt on his quest to follow his principles in the cruel and competitive society of his underground homeland where such feelings are threatened.'},
      {name: 'The Last Unicorn', author: 'Peter S. Beagle', date: 1968, image: LastUnicorn, selected: 'false', description: 'The Last Unicorn is a fantasy novel by American author Peter S. Beagle and published in 1968, by Viking Press in the U.S. and The Bodley Head in the U.K. It follows the tale of a unicorn, who believes she is the last of her kind in the world and undertakes a quest to discover what has happened to the others. It has sold more than five million copies worldwide since its original publication, and has been translated into at least twenty languages (prior to the 2007 edition). In 1987, Locus ranked The Last Unicorn number five among the 33 "All-Time Best Fantasy Novels", based on a poll of subscribers. The 1998 rendition of the poll ranked The Last Unicorn number 18.'},
      {name: 'The Lord of the Rings', author: 'J.R.R. Tolkien', date: 1954, image: LordOfThe, selected: 'false', description: 'The Lord of the Rings is an epic high fantasy novel written by English author and scholar J. R. R. Tolkien. The story began as a sequel to Tolkien\'s 1937 fantasy novel The Hobbit, but eventually developed into a much larger work. Written in stages between 1937 and 1949, The Lord of the Rings is one of the best-selling novels ever written, with over 150 million copies sold. The title of the novel refers to the story\'s main antagonist, the Dark Lord Sauron, who had in an earlier age created the One Ring to rule the other Rings of Power as the ultimate weapon in his campaign to conquer and rule all of Middle-earth. From quiet beginnings in the Shire, a hobbit land not unlike the English countryside, the story ranges across Middle-earth, following the course of the War of the Ring through the eyes of its characters, not only the hobbits Frodo Baggins, Samwise "Sam" Gamgee, Meriadoc "Merry" Brandybuck and Peregrin "Pippin" Took, but also the hobbits\' chief allies and travelling companions: the Men, Aragorn, a Ranger of the North, and Boromir, a Captain of Gondor; Gimli, a Dwarf warrior; Legolas Greenleaf, an Elven prince; and Gandalf, a wizard.'},
      {name: 'The Martian Chronicles', author: 'Ray Bradbury', date: 1950 , image: Martian, selected: 'false', description: 'The Martian Chronicles is a 1950 science fiction short story fixup by Ray Bradbury that chronicles the colonization of Mars by humans fleeing from a troubled and eventually atomically devastated Earth, and the conflict between aboriginalMartians and the new colonists. The book lies somewhere in between a short story collection and an episodic novel, containing stories Bradbury originally published in the late 1940s in science fiction magazines. The stories were loosely woven together with a series of short, interstitial vignettes for publication.'},
      {name: 'Mistborn', author: 'Brandon Sanderson', date: 2006, image: Mistborn, selected: 'false', description: 'Mistborn is a series of epic fantasy novels written by American author Brandon Sanderson and published by Tor Books. The first series, published between 2006 and 2008, consists of The Final Empire, The Well of Ascension, and The Hero of Ages. To prepare readers for the second trilogy, Sanderson wrote a transitional sequel, The Alloy of Law, which then turned into the first installment in the four-book Wax and Wayne series, set 300 years later. The Wax and Wayne book titles are: The Alloy of Law, released on November 8, 2011; Shadows of Self, released on October 6, 2015; The Bands of Mourning, published on January 26, 2016; and The Lost Metal, currently in production. Sanderson also published a companion story to the original trilogy, titled Mistborn: Secret History, on January 26, 2016.'},
      {name: 'The Mists of Avalon', author: 'Marion Zimmer Bradley', date: 1982, image: MistsOf, selected: 'false', description: 'The Mists of Avalon is a 1983 fantasy novel by American writer Marion Zimmer Bradley, in which the author relates the Arthurian legends from the perspective of the female characters. The book follows the trajectory of Morgaine (often called Morgan le Fay in other works), a priestess fighting to save her Celtic culture in a country where Christianity threatens to destroy the pagan way of life. The epic is focused on the lives of Gwenhwyfar, Viviane, Morgause, Igraine and other women of the Arthurian legend. The Mists of Avalon is in stark contrast to most other retellings of the Arthurian tales, which consistently cast Morgan le Fay as a distant, one-dimensional evil sorceress, with little or no explanation given for her antagonism to the Round Table. In this case Morgaine is presented as a woman with unique gifts and responsibilities at a time of enormous political and spiritual upheaval who is called upon to defend her indigenous heritage against impossible odds.'},
      {name: 'The Moon is a Hard Mistress', author: 'Robert A. Heinlein', date: 1966, image: MoonIs, selected: 'false', description: 'The Moon Is a Harsh Mistress is a 1966 science-fiction novel by American writer Robert A. Heinlein, about a lunar colony\'s revolt against rule from Earth. The novel expresses and discusses libertarian ideals. It is respected for its credible presentation of a comprehensively imagined future human society on both the Earth and the Moon. Originally serialized in Worlds of If (December 1965, January, February, March, April 1966), the book was nominated for the Nebula Award in 1966. It received the Hugo Award for best science fiction novel in 1967.'},
      {name: 'The Name of the Wind', author: 'Patrick Rothfuss', date: 2007, image: NameOfThe, selected: 'false', description: 'The Name of the Wind, also called The Kingkiller Chronicle: Day One, is a fantasy novel written by American author Patrick Rothfuss. It is the first book in a series called The Kingkiller Chronicle and followed by The Wise Man\'s Fear. It was published on March 27, 2007 by DAW Books. The book is divided into two timelines: the first in the present, told through a third-person narrator; the second in protagonist Kvothe\'s past, narrated by Kvothe himself. The book also contains a prologue and an epilogue, which are almost word for word identical texts. At the very beginning, the reader hears an old story-teller speaking of a famous old wizard called Taborlin the Great, who was captured by evil beings called the Chandrian. Escaping them, Taborlin fell from a great height—but since he knew the Name of the Wind, he called it and the Wind came and set him down safely. In later parts of the book, characters are often skeptical of such stories. Some kinds of magic are taught in the University as an academic discipline and have daily life applications.'},
      {name: 'Neuromancer', author: 'William Gibson', date: 1984, image: Neuromancer, selected: 'false', description: 'Neuromancer is a 1984 science fiction novel by American-Canadian writer William Gibson. It is one of the best-known works in the cyberpunk genre and the first novel to win the Nebula Award, the Philip K. Dick Award, and the Hugo Award. It was Gibson\'s debut novel and the beginning of the Sprawl trilogy. The novel tells the near-future story of Case, a washed-up computer hacker hired by a mysterious employer for one last job against a powerful artificial intelligence.'},
      {name: 'Neverwhere', author: 'Neil Gaiman', date: 1996 , image: Neverwhere, selected: 'false', description: 'Neverwhere is the companion novelisation written by English author Neil Gaiman of the television serial Neverwhere, by Gaiman and Lenny Henry. The plot and characters are exactly the same as in the series, with the exception that the novel form allowed Gaiman to expand and elaborate on certain elements of the story and restore changes made in the televised version from his original plans. Most notable is the appearance of the Floating Market at Harrods (in the novel) rather than under Battersea power station (the TV series). This is because the management of Harrods changed their minds about proposed filming. The novel was originally released by BBC Books in 1996, three episodes into the television series run. It was accompanied by a spoken word CD and cassette release, also by the BBC.'},
      {name: 'Nineteen Eighty-four', author: 'George Orwell', date: 1953 , image: Nineteen, selected: 'false', description: 'Nineteen Eighty-Four, often published as 1984, is a dystopian novel published in 1949 by English author George Orwell. The novel is set in the year 1984 when most of the world population have become victims of perpetual war, omnipresent government surveillance and propaganda. In the novel, Great Britain ("Airstrip One") has become a province of a superstate named Oceania. Oceania is ruled by the "Party", who employ the "Thought Police" to persecute individualism and independent thinking. The Party\'s leader is Big Brother, who enjoys an intense cult of personality but may not even exist. The protagonist of the novel, Winston Smith, is a rank-and-file Party member. Smith is an outwardly diligent and skillful worker, but he secretly hates the Party and dreams of rebellion against Big Brother. Smith rebels by entering a forbidden relationship with fellow employee Julia. As literary political fiction and dystopian science-fiction, Nineteen Eighty-Four is a classic novel in content, plot, and style. Many of its terms and concepts, such as Big Brother, doublethink, thoughtcrime, Newspeak, Room 101, telescreen, 2 + 2 = 5, and memory hole, have entered into common usage since its publication in 1949.'},
      {name: 'The Once and Future King', author: 'T.H. White', date: 1958 , image: OnceAnd, selected: 'false', description: 'The Once and Future King is a work by T. H. White based upon Le Morte d\'Arthur by Sir Thomas Malory. It was first published in 1958. It collects and revises shorter novels published from 1938 to 1941, with much new material. The Once and Future King contains much deliberately anachronistic humour, affectionate mockery of the source text and commentary on totalitarianism. The work explores human nature regarding power and justice. As the young Arthur becomes king, he attempts to quell the prevalent "might makes right" attitude with his idea of chivalry, even as he foresees the ascendancy of another form of might, namely legal prowess in the courtroom, and a form of fascism outside the courtroom. White\'s title derives from the inscription that, according to Malory\'s Le Morte d\'Arthur, was written upon King Arthur\'s tomb: Hic iacet Arthurus, rex quondam, rexque futurus or "Here lies Arthur, king once, and king to be."'},
      {name: 'The Princess Bride', author: 'William Goldman', date: 1973 , image: PrincessBride, selected: 'false', description: 'The Princess Bride is a 1973 fantasy romance novel by American writer William Goldman. The book combines elements of comedy, adventure, fantasy, romantic love, romance, and fairy tale. It is presented as an abridgment (or "the good parts version") of a longer work by S. Morgenstern, and Goldman\'s "commentary" asides are constant throughout. It was originally published in the United States by Harcourt Brace, then later by Random House, while in the United Kingdom, it was later published by Bloomsbury. The book was adapted into a 1987 feature film, whose screenplay was written by Goldman himself, that was directed by Rob Reiner. William Goldman said, "I\'ve gotten more responses on The Princess Bride than on everything else I\'ve done put together—all kinds of strange outpouring letters. Something in The Princess Bride affects people." A segment of the book was published as "Duel Scene (From The Princess Bride)" in the anthology The Best of All Possible Worlds (1980), which was edited by Spider Robinson. In 2015, a collection of essays on the novel and the film adaptation was published entitled The Princess Bride and Philosophy.'},
      {name: 'Rendezvous with Rama', author: 'Arthur C. Clarke', date: 1973 , image: Rendezvous, selected: 'false', description: 'Rendezvous with Rama is a science fiction novel by British writer Arthur C. Clarke first published in 1973. Set in the 2130s, the story involves a 50-kilometre (31 mi) cylindrical alien starship that enters the Solar System. The story is told from the point of view of a group of human explorers who intercept the ship in an attempt to unlock its mysteries. The novel won both the Hugo and Nebula awards upon its release, and is regarded as one of the cornerstones in Clarke\'s bibliography. The concept was later extended with several sequels. After an asteroid falls in Northeast Italy in 2077, creating a major disaster, the government of Earth sets up the Spaceguardsystem as an early warning of arrivals from deep space.'},
      {name: 'Ringworld', author: 'Larry Niven', date: 1970, image: Ringworld, selected: 'false', description: 'Ringworld is a 1970 science fiction novel by Larry Niven, set in his Known Space universe and considered a classic of science fiction literature. Niven later added four sequels and four prequels. (The Fleet of Worlds series, co-written with Edward M. Lerner, provides the four prequels, as well as Fate of Worlds, the final sequel.) These books tie into numerous other books set in Known Space. Ringworld won the Nebula Award in 1970, as well as both the Hugo Award and Locus Award in 1971. On planet Earth in 2850 AD, Louis Gridley Wu is celebrating his 200th birthday. Despite his age, Louis is in perfect physical condition (due to the longevity drug boosterspice). He has once again become bored with human society and is thinking about taking one of his periodic sabbaticals, alone in a spaceship far away from other people. He meets Nessus, a Pierson\'s puppeteer, who offers him a mysterious job. Intrigued, Louis eventually accepts. Speaker-to-Animals (Speaker), who is a Kzin, and Teela Brown, a young human woman who becomes Louis\' lover, also join the crew.'},
      {name: 'The Silmarillion', author: 'J.R.R. Tolkien', date: 1977, image: Silmarillion, selected: 'false', description: 'The Silmarillion is a collection of mythopoeic works by English writer J. R. R. Tolkien, edited and published posthumously by his son, Christopher Tolkien, in 1977, with assistance from Guy Gavriel Kay. The Silmarillion, along with J. R. R. Tolkien\'s other works, forms an extensive, though incomplete, narrative that describes the universe of Eä in which are found the lands of Valinor, Beleriand, Númenor, and Middle-earth, within which The Hobbit and The Lord of the Rings take place. The Silmarillion comprises five parts. The first part, Ainulindalë, tells of the creation of Eä, the "world that is". Valaquenta, the second part, gives a description of the Valar and Maiar, the supernatural powers in Eä. The next section, Quenta Silmarillion, which forms the bulk of the collection, chronicles the history of the events before and during the First Age, including the wars over the Silmarils that gave the book its title. The fourth part, Akallabêth, relates the history of the Downfall of Númenor and its people, which takes place in the Second Age. The final part, Of the Rings of Power and the Third Age, is a brief account of the circumstances which led to and were presented in The Lord of the Rings.'},
      {name: 'Slaughterhouse Five', author: 'Kurt Vonnegut, Jr.', date: 1969, image: Slaughterhouse, selected: 'false', description: 'Slaughterhouse-Five, or The Children\'s Crusade: A Duty-Dance with Death (1969) is a science fiction-infused anti-war novel by Kurt Vonnegut about the World War II experiences and journeys through time of Billy Pilgrim, from his time as an American soldier and chaplain\'s assistant, to postwar and early years. It is generally recognized as Vonnegut\'s most influential and popular work. A central event is Pilgrim\'s surviving the Allies\' firebombing of Dresden as a prisoner-of-war. This was an event in Vonnegut\'s own life, and the novel is considered semi-autobiographical. The story is told in a nonlinear order, and events become clear through flashbacks (or time travel experiences) from the unreliable narrator. He describes the stories of Billy Pilgrim, who believes he was held in an alien zoo and has experienced time travel.'},
      {name: 'Snow Crash', author: 'Neal Stephenson', date:1992, image: SnowCrash, selected: 'false', description: 'Snow Crash is a science fiction novel by American writer Neal Stephenson, published in 1992. Like many of Stephenson\'s other novels it covers history, linguistics, anthropology, archaeology, religion, computer science, politics, cryptography, memetics and philosophy. Stephenson explained the title of the novel in his 1999 essay "In the Beginning... Was the Command Line" as his term for a particular software failure mode on the early Apple Macintosh computer. Stephenson wrote about the Macintosh that "When the computer crashed and wrote gibberish into the bitmap, the result was something that looked vaguely like static on a broken television set—a \'snow crash\' ". The book presents the Sumerian language as the firmware programming language for the brainstem, which is supposedly functioning as the BIOS for the human brain. According to characters in the book, the goddess Asherah is the personification of a linguistic virus, similar to a computer virus. The god Enki created a counter-program which he called a nam-shub that caused all of humanity to speak different languages as a protection against Asherah (a re-interpretation of the ancient Near Eastern story of the Tower of Babel).'},
      {name: 'Starship Troopers', author: 'Robert Heinlein', date: 1959, image:Starship, selected: 'false', description: 'Starship Troopers is a military science fiction novel by American writer Robert A. Heinlein. Written in a few weeks in reaction to the U.S. suspending nuclear tests, the story was first published as a two-part serial in The Magazine of Fantasy & Science Fiction as Starship Soldier, and published as a book by G. P. Putnam\'s Sons in December 1959. The story is set in a future society ruled by a world government dominated by a military elite. The first-person narrativefollows Juan "Johnny" Rico through his military service in the Mobile Infantry. Rico progresses from recruit to officeragainst the backdrop of an interstellar war between humans and an alien species known as "Arachnids" or "Bugs". Interspersed with the primary plot are classroom scenes in which Rico and others discuss philosophical and moral issues, including aspects of suffrage, civic virtue, juvenile delinquency, and war; these discussions have been described as expounding Heinlein\'s own political views. Starship Troopers has been identified with a tradition of militarism in U.S. science fiction, and draws parallels between the conflict between humans and the Bugs, and the Cold War.'},
      {name: 'Stranger in a Strange Land', author: 'Robert A. Heinlein', date: 1961, image: StrangerIn, selected: 'false', description: 'Stranger in a Strange Land is a 1961 science fiction novel by American author Robert A. Heinlein. It tells the story of Valentine Michael Smith, a human who comes to Earth in early adulthood after being born on the planet Mars and raised by Martians. The novel explores his interaction with—and eventual transformation of—Terran culture. In 2012, the US Library of Congress named it one of 88 "Books that Shaped America". The title "Stranger in a Strange Land" is an allusion to the phrase in Exodus 2:22. According to Heinlein, the novel\'s working title was The Heretic. In 1991, three years after Heinlein\'s death, his widow, Virginia Heinlein, arranged to have the original uncut manuscript published. Critics disagree about which version is superior, though Heinlein preferred the original manuscript and described the heavily edited version as "telegraphese".'},
      {name: 'The Time Machine', author: 'H.G. Wells', date: 1895 , image: TimeMachine, selected: 'false', description: 'The Time Machine is a science fiction novella by H. G. Wells, published in 1895 and written as a frame narrative. The work is generally credited with the popularization of the concept of time travel by using a vehicle that allows an operator to travel purposely and selectively forwards or backwards in time. The term "time machine", coined by Wells, is now almost universally used to refer to such a vehicle. The Time Machine has been adapted into three feature films of the same name, as well as two television versions, and a large number of comic book adaptations. It has also indirectly inspired many more works of fiction in many media productions.'},
      {name: 'The War of the Worlds', author: 'H.G. Wells', date: 1898 , image: WarOfThe, selected: 'false', description: 'The War of the Worlds is a science fiction novel by English author H. G. Wells, first serialised in 1897 by Pearson\'s Magazine in the UK and by Cosmopolitan magazine in the US. Written between 1895 and 1897, it is one of the earliest stories to detail a conflict between mankind and an extraterrestrial race. The novel is the first-person narrative of both an unnamed protagonist in Surrey and of his younger brother in London as southern England is invaded by Martians. The plot has been related to invasion literature of the time. The novel has been variously interpreted as a commentary on evolutionary theory, British imperialism, and generally Victorian superstitions, fears and prejudices. At the time of publication, it was classified as a scientific romance, like Wells\' earlier novel The Time Machine. The War of the Worldshas been both popular (having never been out of print) and influential, spawning half a dozen feature films, radio dramas, a record album, various comic book adaptations, a television series, and sequels or parallel stories by other authors. It was most memorably dramatized in a 1938 radio program that allegedly caused public panic among listeners who did not know the Martian invasion was fictional.'},
      {name: 'Watership Down', author: 'Richard Adams', date: 1972, image: WatershipDown, selected: 'false', description: 'Watership Down is a survival and adventure novel by English author Richard Adams, published by Rex Collings Ltd of London in 1972. Set in southern England, the story features a small group of rabbits. Although they live in their natural environment, they are anthropomorphised, possessing their own culture, language, proverbs, poetry, and mythology. Evoking epic themes, the novel follows the rabbits as they escape the destruction of their warren and seek a place to establish a new home, encountering perils and temptations along the way. Watership Down was Richard Adams\' first novel. Although it was rejected by several publishers before Collings accepted it, it won the annual Carnegie Medal, annual Guardian Prize, and other book awards. It was adapted into an animated feature film in 1978, and later a television series which ran from 1999 to 2001. Adams completed a sequel almost 25 years later, Tales from Watership Down (Random House, 1996; Hutchinson and Alfred A. Knopf imprints). It is a collection of 19 short stories about El-ahrairah and the rabbits of the Watership Down warren, with "Notes on Pronunciation" and "Lapine Glossary".'},
      {name: 'The Way of Kings', author: 'Brandon Sanderson', date:2010 , image: WayOfKings, selected: 'false', description: 'The Way of Kings is an epic fantasy novel written by American author Brandon Sanderson and the first book in The Stormlight Archive series. The novel was published on August 31, 2010 by Tor Books. The Way of Kings consists of one prelude, one prologue, 75 chapters, an epilogue and 9 interludes. It was followed by Words of Radiance in 2014. The story rotates between the points of view of Kaladin, Shallan Davar, Szeth-son-son-Vallano, Dalinar Kholin, and several other minor characters, who lead seemingly unconnected lives. Szeth, a Shin man cast out by his people and condemned to obey his constantly changing masters, is sent to murder the king of one of the world\'s most powerful nations, Alethkar. As the story progresses, he continuously changes hands, doing his best to hide the fact that he possesses an Honorblade, a mythical blade used by the Heralds that can cut through any material. He also possesses an ability to bind things together for a certain amount of time (“Surgebinding”), once possessed by the Knights Radiant and thought lost, making him incredibly difficult to defeat in battle.'}
    ]
  }



  selectBookHandler = (bookToSelect) => {
    let bookList = Object.assign([], this.state.books);
    bookList.forEach(function(obj){
      if(obj.name === bookToSelect){
        obj.selected = true;
      } else {
        obj.selected = false;
      }
    })
    this.setState({books:bookList, displayAll:false})
  }

  selectAllBooks = () => {
    let bookList = Object.assign([], this.state.books);
    bookList.forEach(function(obj){
        obj.selected = false;
    })
    this.setState({books:bookList, displayAll: true})
  }

  render() {
    let allBooks = (this.state.displayAll) ?
    (this.state.books.map((book)=><BookCard
      key={book.name}
      title={book.name}
      year={book.date}
      author={book.author}
      image={book.image}
      selectBook={this.selectBookHandler}
    />)) : null

    let selectedBook = this.state.books.filter((book)=>book.selected === true).map((book)=><BookSummary
      key={book.name}
      title={book.name}
      year={book.date}
      author={book.author}
      image={book.image}
      description={book.description}
      selectAll={this.selectAllBooks}
    />)


    return (
      <div className="App">
        <header>
          <h1>Top SciFi & Fantasy Books</h1>
        </header>
        <main>
          <nav>
            <p className={this.state.displayAll===true ? "selected" : "bookNav"} onClick={()=>this.selectAllBooks()}>View All Books</p>
          {this.state.books.map((book)=><p className={book.selected===true ? "selected" : "bookNav"} onClick={()=>this.selectBookHandler(book.name)} key={book.name}>{book.name}</p>)}
          </nav>
          <article className="display">
            {allBooks}
            {selectedBook}
          </article>

        </main>
      </div>
    );
  }
}

const BookCard = (props) => {
  return(
    <div className="card" onClick={()=>props.selectBook(props.title)}>
      <h3>{props.title}</h3>
      <img src={props.image} alt={props.title}/>
      <p>{props.author} ({props.year})</p>
    </div>
  );
}

const BookSummary = (props) => {
  return(
    <div className="book-summary">
      <button className="back-button" onClick={()=>props.selectAll()}>Back to All</button>
      <div className="summaryCard">
        <img src={props.image} alt={props.title}/>
        <div className="description">
          <h1>{props.title}</h1>
          <p className="book-author">By: {props.author}</p>
          <p className="book-year">Written: {props.year}</p>
          <div className="description-text">{props.description}</div>
        </div>
      </div>
    </div>

  )
}

export default App;
